### ISSUE TITLE
au run - invalid command ; clearing npm cache doesn't help.

### ISSUE THREAD

**Issue by sheshmantha** [aurelia/app-ux-showcase#1]
**I'm submitting a bug report**

* **Library Version:**
au - 0.21.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.9.1

* **NPM Version:**
3.10.9

* **JSPM OR Webpack AND Version**
JSPM 0.16.32 | webpack 2.1.0-beta.17

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
all | TypeScript X.X | ESNext

**Current behavior:**
1. git clone app-ux-showcase repo 
1. au run -- gives error of "invalid command"
1. cleared npm cache by uninstalling cli, removing npm cache and reinstalling cli
1. still same problem

**Expected/desired behavior:**

* **What is the expected behavior?**
I expected that I could see the ux showcase :)

* **What is the motivation / use case for changing the behavior?**

**Comment by miroslavpopovic** [comment]
@sheshmantha Have you run `npm install` prior to trying `au run`? I don't see it in your "Current behavior" steps, so that's probably an issue.

**Comment by EisenbergEffect** [comment]
Please run `npm install` with npm 3.

**Comment by sheshmantha** [comment]
I had run it... simply forgot to catalog it in the list of things...
Will try again.
