### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'anchorIsContainer' of undefined 

### ISSUE THREAD

**Issue by lmj0011** [aurelia/app-ux-showcase#10]
**I'm submitting a bug report**

* **Library Version:**
au v0.21.0

**Please tell us about your environment:**
* **Operating System:**
Linux (Xubuntu)

* **Node Version:**
6.9.1

* **NPM Version:**
3.10.8

* **JSPM OR Webpack AND Version**
JSPM 0.16.39

* **Browser:**
Chrome 54

* **Language:**
TypeScript ">=1.9.0-dev || ^2.0.0"

**Current behavior:**
I followed the instructions for installing the ux showcase.

when I load the app in the browser I get an TypeError

`Unhandled rejection TypeError: Cannot read property 'anchorIsContainer' of undefined | vendor-bundle.js:1399`

![p1](https://cloud.githubusercontent.com/assets/9396189/20862649/4c013826-b976-11e6-8a04-25fcaf81b413.png)

**Expected/desired behavior:**

* **What is the expected behavior?**
app to start

**Comment by EisenbergEffect** [comment]
Closing as a duplicate. It's a regression in templating. Fix is going out today.

**Comment by lmj0011** [comment]
>Fix is going out today.

:question:

**Comment by Thanood** [comment]
https://github.com/aurelia/templating/issues/503
fixed in https://github.com/aurelia/templating/commit/d1d1fe457ec845e19027db344f9ba199214ef7db

**Comment by lmj0011** [comment]
alright, waiting for  `aurelia-animator-css` to get it's `aurelia-templating` updated to the recent version.

https://github.com/aurelia/animator-css/blob/master/package.json
