### ISSUE TITLE
au test failed

### ISSUE THREAD

**Issue by khuongduybui** [aurelia/app-ux-showcase#12]
**I'm submitting a bug report**

* **Library Version:**
0.1.0 (latest master)

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.2.1

* **NPM Version:**
3.10.9

* **Browser:**
Chrome 55.0.2883

* **Language:**
TypeScript

**Current behavior:**
au build
au test
```
Chrome 55.0.2883 (Windows 10 0.0.0) the app says hello FAILED
        TypeError: Cannot read property 'design' of undefined
            at new App (scripts/app-bundle.js:14:15)
            at Object.<anonymous> (test/unit/app.spec.js:5:20)
```

**Comment by EisenbergEffect** [comment]
This is a bogus test. We'll remove it.
