### ISSUE TITLE
au run --env dev on windows 10 ->throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by niedarek** [aurelia/app-ux-showcase#15]
**I'm submitting a bug report**

* **Library Version:**
major.minor.patch-pre

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.10 lts

* **NPM Version:**
3.10

* **JSPM OR Webpack AND Version**

* **Browser:**
cli

* **Language:**
all | TypeScript X.X | ESNext

**Current behavior:**
E:\app-ux-showcase-master>au run --env dev

Starting 'readProjectConfiguration'...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: File not found with singular glob: E:\app-ux-showcase-master\node_modules\aurelia-ux\dist\amd\input\ux-input.html
    at Glob.<anonymous> (E:\app-ux-showcase-master\node_modules\glob-stream\index.js:41:11)
    at Glob.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:188:7)
    at Glob._finish (E:\app-ux-showcase-master\node_modules\glob-stream\node_modules\glob\glob.js:172:8)
    at done (E:\app-ux-showcase-master\node_modules\glob-stream\node_modules\glob\glob.js:159:12)
    at Glob._processSimple2 (E:\app-ux-showcase-master\node_modules\glob-stream\node_modules\glob\glob.js:652:12)
    at E:\app-ux-showcase-master\node_modules\glob-stream\node_modules\glob\glob.js:640:10
    at Glob._stat2 (E:\app-ux-showcase-master\node_modules\glob-stream\node_modules\glob\glob.js:736:12)
    at lstatcb_ (E:\app-ux-showcase-master\node_modules\glob-stream\node_modules\glob\glob.js:728:12)

**Expected/desired behavior:**
run ux-showcase to admire :)

**Comment by ZHollingshead** [comment]
I will take a closer look when I get to work in about 40 minutes, but off the top of my head until a new release is prepared for Aurelia UX you will need to pull down the UX project and build it. Once this is done run `au update-ux` in the showcase app with the two projects next to each other to pull the latest ux code into the showcase.

**Comment by ZHollingshead** [comment]
This issue should be resolved when @EisenbergEffect makes a new release for Aurelia UX. Here is a more step by step instruction on what to do in the meantime. This is relying on some files that are only in the Development version of the Aurelia UX library so first, both projects need to be cloned into the same directory.

Next, run `npm run build` on the Aurelia UX library, which should kick off the build process.

After the build process for Aurelia UX is complete, switch to the App UX Showcase directory and run `au update-ux` which will pull the development build into the showcase application's node_modules folder. When that is done run `au run` and the application should work as expected.

**Comment by 4deeptech** [comment]
To clear up any confusion.  Clone both so that they are side by side in a folder like sample below.

SomeRootFolderWhereYouCloneTo
-ux
-app-ux-showcase

Run:
 `npm install` in each one. 

In 'ux' folder run: 

`npm run build`

Then in the 'app-ux-showcase' folder, run:
`au update-ux` and it will scan and find the 'ux' folder and copy over what is needed. Then in the same 'app-ux-showcase' folder, run: 

`au run --env dev`
