### ISSUE TITLE
AU requires higher version of NodeJS

### ISSUE THREAD

**Issue by LarsKemmann** [aurelia/app-ux-showcase#16]
**I'm submitting a bug report**

* **Library Version:**
n/a

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
4.5.0

* **NPM Version:**
3.10.7

* **JSPM OR Webpack AND Version**
JSPM 0.16.46

* **Browser:**
all

* **Language:**
all

**Current behavior:**
The readme.md file suggests that Node >= 4.x is supported. However, I had to upgrade my Node.js version from what is shown above, otherwise I got the following error when trying to run the latest `au`:

> C:\Users\LarsKemmann\AppData\Roaming\npm\node_modules\aurelia-cli\lib\resolve\index.js:1
> (function (exports, require, module, __filename, __dirname) { let core = require('./lib/core');
>                                                               ^^^
> 
> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:373:25)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (C:\Users\LarsKemmann\AppData\Roaming\npm\node_modules\aurelia-cli\bin\aurelia-cli.js:3:17)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)

**Expected/desired behavior:**

* **What is the expected behavior?**
If only the latest (fully patched 4.x.x?) LTS versions of Node are supported, please note that. I don't know if that would have worked in my case, so if only newer versions of Node (as in my case, 7.7.4) are supported, please note that. Thanks!

* **What is the motivation / use case for changing the behavior?**
Removing a user adoption hurdle. I got my version of Node on this particular machine from a Visual Studio 2015 or 2017 install, I think.

**Comment by EisenbergEffect** [comment]
@JeroenVinke Can you take a look at the CLI source and see if we accidentally omitted the "use strict" on any of the files? I think it's causing a Node issue for older installs.

**Comment by LarsKemmann** [comment]
Thanks so much!

**Comment by ReneButcher** [comment]
I'm trying to follow along with the GettingStarted video at aurelia.io and get this same error.
(I installed aurelia today)
I created the todo.js, app.js, app.html and get the errors below when executing: au run --watch

Tracing aurelia-testing...
{ uid: 11,
  name: 'writeBundles',
  branch: false,
  error: [SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode],
  duration: [ 1, 783374168 ],
  time: 1495498655627 }
{ uid: 2,
  name: '<series>',
  branch: true,
  error: [SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode],
  duration: [ 2, 287503271 ],
  time: 1495498655654 }
{ uid: 1,
  name: '<series>',
  branch: true,
  error: [SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode],
  duration: [ 2, 312206442 ],
  time: 1495498655678 }
{ uid: 0,
  name: '<series>',
  branch: true,
  error: [SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode],
  duration: [ 2, 336993296 ],
  time: 1495498655702 }
[SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode]

**Comment by JeroenVinke** [comment]
@ReneButcher Sorry to hear that. We've seen that it installs a slightly older version of the CLI. Try running `npm install aurelia-cli@0.29.0 --save-dev` in the project directory. We have a PR that's going to make sure that this doesn't happen again in the future: https://github.com/aurelia/cli/pull/603

**Comment by ReneButcher** [comment]
Thank you for your reply.
After “install aurelia-cli@0.29.0<mailto:aurelia-cli@0.29.0> --save-dev”,
I attempted “au new” and got a different error below:
…
Project structure created and configured.

Would you like to install the project dependencies?

1. Yes (Default)
   Installs all server, client and tooling dependencies needed to build the project.
2. No
   Completes the new project wizard without installing dependencies.

[Yes]> 1

Installing project dependencies.
Uncaught promise rejection:
{ [Error: Cannot find module 'graceful-fs'] code: 'MODULE_NOT_FOUND' }

**Comment by ReneButcher** [comment]
Thank you...resolved by installing latest NodeJS for windows
