### ISSUE TITLE
Icon of button type fab is not centred in Firefox

### ISSUE THREAD

**Issue by Gheoan** [aurelia/app-ux-showcase#7]
**I'm submitting a bug report**

* **Library Version:**
master

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Browser:**
Firefox 49

**Current behavior:**
Firefox: ![button_firefox](https://cloud.githubusercontent.com/assets/9906612/20195483/704d8efc-a79f-11e6-9e5a-009a9ea7d7eb.png)

**Expected/desired behavior:**

* **What is the expected behavior?**
Chrome: ![button_chrome](https://cloud.githubusercontent.com/assets/9906612/20195510/9640519e-a79f-11e6-9b0e-7188d8474adb.png)
* **What is the motivation / use case for changing the behavior?**

**Comment by AStoker** [comment]
Same holds true for Safari. Buttons slightly offset.

**Comment by EisenbergEffect** [comment]
Yes. I have confirmed.

**Comment by Gheoan** [comment]
I believe this is caused by inconsistent default `line-height` value across browsers. Including a CSS reset might solve this and prevent further similar issues.

**Comment by EisenbergEffect** [comment]
We've got one but it may be missing that. I'll check. Thanks!

**Comment by moodledan** [comment]
I modified reset.css to fix the alignment issue, appears to be working. 

I've borrowed from [normalize.css](https://raw.githubusercontent.com/necolas/normalize.css/master/normalize.css) and dropped in a few lines at the end of reset.css.

Gist here (see lines 49 - 65): https://gist.github.com/moodledan/fe3bd99f1575a35284641c9a921abfe8#file-reset-css-L49-L65

**Comment by EisenbergEffect** [comment]
Can you submit a PR?

**Comment by mttmccb** [comment]
Looks like this can be closed it was merged in November

**Comment by Gheoan** [comment]
I just checked and it is fixed.
